#!/usr/bin/env python3
"""
Deploy blog content to Kubernetes.

日常发布请直接 push 到 main 分支，由 GitHub Actions 自动完成。
本脚本仅用于应急调试场景（kubectl 直连集群手动同步）。
"""
from __future__ import annotations

import io
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tarfile
import time


def _parse_frontmatter_date(readme: pathlib.Path, key: str) -> str:
    """Parse a date field from README frontmatter. Returns empty string if not found."""
    with readme.open("r", encoding="utf-8") as f:
        content = f.read()
    match = re.search(rf"^{key}:\s*\"?([^\"]+)\"?", content, re.MULTILINE)
    return match.group(1).strip() if match else ""


def _sidebar_sort_key(folder: pathlib.Path) -> str:
    """Sort key: most recent updated_at first, fallback to created_at, then empty."""
    readme = folder / "README.md"
    if readme.exists():
        updated = _parse_frontmatter_date(readme, "updated_at")
        if updated:
            return updated
        created = _parse_frontmatter_date(readme, "created_at")
        if created:
            return created
    return ""


def _article_dirs(root: pathlib.Path) -> list[pathlib.Path]:
    """Get list of article directories (contain README.md)."""
    visible_names = {
        "assets", "repos", ".github", ".agent", "node_modules",
    }
    return [
        d for d in root.iterdir()
        if d.is_dir()
        and not d.name.startswith(".")
        and d.name not in visible_names
        and not d.name.startswith("_")
        and (d / "README.md").exists()
    ]


def _parse_frontmatter_title(readme: pathlib.Path) -> str:
    """Parse H1 title from README. Falls back to directory name."""
    with readme.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("# "):
                return line[2:].strip()
    return readme.parent.name


def generate_sidebar(root: pathlib.Path) -> None:
    """Generate minimal _sidebar.md — just a home link.
    The article's table of contents is auto-generated by docsify via subMaxLevel."""
    (root / "_sidebar.md").write_text("- [首页](\/)\n", encoding="utf-8")
    print("  Sidebar generated: minimal (home link only)")


def generate_posts_json(root: pathlib.Path) -> list[dict]:
    """Generate posts.json with article metadata. Returns posts list."""
    dirs = _article_dirs(root)
    posts = []
    for folder in dirs:
        readme = folder / "README.md"
        title = _parse_frontmatter_title(readme)
        created_at = _parse_frontmatter_date(readme, "created_at")
        updated_at = _parse_frontmatter_date(readme, "updated_at") or created_at
        posts.append({
            "title": title,
            "path": f"{folder.name}/README.md",
            "created_at": created_at,
            "updated_at": updated_at,
        })

    posts.sort(key=lambda p: p["updated_at"], reverse=True)

    (root / "posts.json").write_text(
        json.dumps(posts, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"  posts.json generated: {len(posts)} posts")
    return posts


def _fmt_date(date_str: str) -> str:
    """Format timestamp like '2026-06-12 17:33:57 +0800' → '2026-06-12'."""
    return date_str[:10] if len(date_str) >= 10 else date_str


def _url_path(path: str) -> str:
    """URL-encode spaces in path for markdown links."""
    return path.replace(" ", "%20")


def _read_root_readme(root: pathlib.Path) -> str:
    """Read root README.md and return content after the first title line."""
    readme_path = root / "README.md"
    if not readme_path.exists():
        return ""
    content = readme_path.read_text(encoding="utf-8")
    # strip the first "# Title" line
    parts = content.split("\n", 1)
    return parts[1].strip() + "\n" if len(parts) > 1 else ""


def generate_home_page(root: pathlib.Path, posts: list[dict]) -> None:
    """Generate home.md — a timeline page rendered natively by docsify."""
    lines = ["# Zexi's Blog\n"]
    lines.append(_read_root_readme(root))

    # Group by year
    year_groups: dict[str, list[dict]] = {}
    for p in posts:
        year = p["updated_at"][:4]
        year_groups.setdefault(year, []).append(p)

    for year in sorted(year_groups.keys(), reverse=True):
        lines.append(f"\n## {year} 年\n")
        items = year_groups[year]

        # Group by month within year
        month_groups: dict[str, list[dict]] = {}
        for p in items:
            m = p["updated_at"][5:7]
            month_groups.setdefault(m, []).append(p)

        for month in sorted(month_groups.keys(), reverse=True):
            lines.append(f"\n### {int(month)} 月\n")
            for p in month_groups[month]:
                date = _fmt_date(p["updated_at"])
                link = _url_path(p["path"])
                lines.append(f"- <span class=\"tl-date\">{date}</span>  [{p['title']}]({link})")

    lines.append("")
    (root / "home.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"  home.md generated: {len(posts)} posts")



def _blog_root() -> pathlib.Path:
    env_root = os.environ.get("BLOG_ROOT")
    if env_root:
        return pathlib.Path(env_root).resolve()

    here = pathlib.Path(__file__).resolve().parent
    for candidate in (here, *here.parents):
        if (candidate / ".git").exists():
            return candidate
    return here.parent.parent


ROOT = _blog_root()
SKILL_DIR = ROOT / ".agent" / "skills" / "deploy"
MANIFEST = pathlib.Path(os.environ.get("BLOG_MANIFEST", str(SKILL_DIR / "blog-deploy.yaml")))
KUBECTL = shutil.which(os.environ.get("KUBECTL_BIN", "kubectl"))
NAMESPACE = os.environ.get("TARGET_NAMESPACE", "blog")
POD_SELECTOR = os.environ.get("TARGET_POD_QUERY", "app=blog")
LOCAL_PATH = pathlib.Path(os.environ.get("LOCAL_BLOG_PATH", str(ROOT)))
RETRY_COUNT = 2
RETRY_DELAY = 3


def main() -> None:
    if not KUBECTL:
        print("kubectl not found. Set KUBECTL_BIN env or install kubectl.")
        sys.exit(1)

    if not MANIFEST.exists():
        print(f"Deploy manifest not found: {MANIFEST}")
        sys.exit(1)

    os.chdir(ROOT)
    print(f"  Root: {ROOT}")

    # 1. Generate sidebar, posts metadata & timeline homepage
    print("  Generating sidebar...")
    generate_sidebar(ROOT)
    print("  Generating posts metadata...")
    posts = generate_posts_json(ROOT)
    print("  Generating timeline homepage...")
    generate_home_page(ROOT, posts)

    # 2. Apply K8s manifest
    print("  Applying manifest...")
    subprocess.run([KUBECTL, "apply", "-f", str(MANIFEST)], check=True)

    # 3. Wait for rollout
    print("  Waiting for rollout...")
    subprocess.run(
        [KUBECTL, "-n", NAMESPACE, "rollout", "status", "deploy/blog", "--timeout=120s"],
        check=True,
    )

    # 4. Find the blog pod
    result = subprocess.run(
        [KUBECTL, "-n", NAMESPACE, "get", "pod", "-l", POD_SELECTOR,
         "-o", "jsonpath={.items[0].metadata.name}"],
        capture_output=True, text=True, check=True,
    )
    pod = result.stdout.strip()
    if not pod:
        print(f"No blog pod found with selector: {POD_SELECTOR}")
        sys.exit(1)
    print(f"  Pod: {pod}")

    # 5. Sync content via tar pipe
    print("  Syncing content...")
    subprocess.run(
        [KUBECTL, "exec", "-i", "-n", NAMESPACE, pod, "--",
         "rm", "-rf", "/usr/share/nginx/html/*"],
        check=True,
    )

    for attempt in range(1, RETRY_COUNT + 1):
        print(f"  Sync attempt {attempt}...")
        try:
            _sync_via_tar(pod)
            print("  Sync succeeded")
            return
        except subprocess.CalledProcessError:
            if attempt == RETRY_COUNT:
                print("  Sync failed")
                sys.exit(1)
            time.sleep(RETRY_DELAY)


def _sync_via_tar(pod: str) -> None:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for entry in sorted(LOCAL_PATH.iterdir()):
            if entry.name == ".git":
                continue
            tar.add(str(entry), arcname=entry.name)
    buf.seek(0)

    subprocess.run(
        [KUBECTL, "exec", "-i", "-n", NAMESPACE, pod, "--",
         "tar", "-xf", "-", "-C", "/usr/share/nginx/html"],
        input=buf.read(),
        check=True,
    )


if __name__ == "__main__":
    main()
